# Generated by Django 2.0.4 on 2018-04-20 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oderascrumy', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scrumyuser',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='scrumyuser',
            name='last_name',
        ),
    ]
