# Generated by Django 2.0.4 on 2018-04-23 07:45

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('oderascrumy', '0002_auto_20180420_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrumygoals',
            name='user_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='oderascrumy.ScrumyUser'),
        ),
        migrations.AddField(
            model_name='scrumyuser',
            name='role',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('OWNER', 'OWNER'), ('ADMIN', 'ADMIN'), ('QA', 'QUALITY ANALYST'), ('DEV', 'DEVELOPER')], max_length=18, null=True),
        ),
    ]
