# Generated by Django 2.0.4 on 2018-04-23 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oderascrumy', '0003_auto_20180423_0845'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scrumygoals',
            name='goal_name',
        ),
        migrations.AddField(
            model_name='scrumygoals',
            name='status_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='oderascrumy.GoalStatus'),
        ),
        migrations.AlterField(
            model_name='goalstatus',
            name='description',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='goalstatus',
            name='title',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='scrumyuser',
            name='location',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='scrumyuser',
            name='name',
            field=models.CharField(max_length=254),
        ),
    ]
