# Generated by Django 2.0.4 on 2018-04-23 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oderascrumy', '0004_auto_20180423_1847'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scrumygoals',
            old_name='date_created',
            new_name='date_of_status_change',
        ),
        migrations.RemoveField(
            model_name='scrumygoals',
            name='date_updated',
        ),
    ]
