# Generated by Django 2.0.4 on 2018-04-24 12:51

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('oderascrumy', '0005_auto_20180423_1919'),
    ]

    operations = [
        migrations.AddField(
            model_name='goalstatus',
            name='status',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('DT', 'Daily Task'), ('WT', 'Weekly Task'), ('V', 'Verified'), ('D', 'Done')], max_length=9, null=True),
        ),
    ]
