# Generated by Django 2.0.4 on 2018-04-24 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oderascrumy', '0006_goalstatus_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scrumygoals',
            name='date_of_status_change',
        ),
    ]
