# Generated by Django 2.0.4 on 2018-04-28 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oderascrumy', '0007_remove_scrumygoals_date_of_status_change'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goalstatus',
            name='status',
            field=models.CharField(choices=[('DT', 'Daily Task'), ('WT', 'Weekly Task'), ('V', 'Verified'), ('D', 'Done')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='scrumygoals',
            name='goal_status',
            field=models.CharField(choices=[('C', 'Completed'), ('O', 'Ongoing'), ('P', 'Pending')], default='1', max_length=2),
        ),
        migrations.AlterField(
            model_name='scrumygoals',
            name='goal_type',
            field=models.CharField(choices=[('1', 'daily goals'), ('2', 'weekly goals'), ('3', 'completed goals')], default='DT', max_length=2),
        ),
        migrations.AlterField(
            model_name='scrumyuser',
            name='role',
            field=models.CharField(choices=[('OWNER', 'OWNER'), ('ADMIN', 'ADMIN'), ('QA', 'QUALITY ANALYST'), ('DEV', 'DEVELOPER')], max_length=2, null=True),
        ),
    ]
