# Generated by Django 2.0.4 on 2018-04-28 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oderascrumy', '0009_auto_20180428_1332'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goalstatus',
            name='status',
        ),
        migrations.RemoveField(
            model_name='scrumygoals',
            name='goal_status',
        ),
        migrations.RemoveField(
            model_name='scrumygoals',
            name='goal_type',
        ),
        migrations.RemoveField(
            model_name='scrumyuser',
            name='roles',
        ),
    ]
