# Generated by Django 2.0.4 on 2018-04-28 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oderascrumy', '0010_auto_20180428_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='goalstatus',
            name='status',
            field=models.CharField(choices=[('DT', 'Daily Task'), ('WT', 'Weekly Task'), ('V', 'Verified'), ('D', 'Done')], default='DT', max_length=2),
        ),
        migrations.AddField(
            model_name='scrumygoals',
            name='goal_status',
            field=models.CharField(choices=[('C', 'Completed'), ('O', 'Ongoing'), ('P', 'Pending')], default='C', max_length=1),
        ),
        migrations.AddField(
            model_name='scrumygoals',
            name='goal_type',
            field=models.CharField(choices=[('1', 'daily goals'), ('2', 'weekly goals'), ('3', 'completed goals')], default='DT', max_length=2),
        ),
        migrations.AddField(
            model_name='scrumyuser',
            name='roles',
            field=models.CharField(choices=[('OWNER', 'OWNER'), ('ADMIN', 'ADMIN'), ('QA', 'QUALITY ANALYST'), ('DEV', 'DEVELOPER')], default='OWNER', max_length=5),
        ),
    ]
