# Generated by Django 2.0.4 on 2018-04-29 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oderascrumy', '0011_auto_20180428_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='goalstatus',
            name='task_id',
            field=models.IntegerField(default=700),
        ),
    ]
