# Generated by Django 2.0.4 on 2018-04-29 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oderascrumy', '0012_goalstatus_task_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goalstatus',
            name='task_id',
            field=models.IntegerField(default=1),
        ),
    ]
